{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.echoellet",
    "module": "controlify-forgified",
    "version": "2.1.2-mc1.20.1-forge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "controlify-forgified-2.1.2-mc1.20.1-forge-sources.jar",
          "url": "controlify-forgified-2.1.2-mc1.20.1-forge-sources.jar",
          "size": 1977920,
          "sha512": "c4f7132f1d6ad3bfacc6abedc1fcd568396c9535999ab26d51eb2694922e8fb4b6a10dd84d8548c195c3385058ef2647e836a93e38772d1a52440839995def39",
          "sha256": "a025b396dd8f2d16aa9f326fccb9ae74aacc1ff1cf7cb9ff9b1d3d02b3dcced8",
          "sha1": "66904c4262637b44533672190122ddf7b338e5a6",
          "md5": "c0628badfcaabba12e74f0c9d48603c6"
        }
      ]
    },
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "controlify-forgified-2.1.2-mc1.20.1-forge.jar",
          "url": "controlify-forgified-2.1.2-mc1.20.1-forge.jar",
          "size": 6946940,
          "sha512": "dfff22afb23f70f51fb81391257c7cfe48f3031a37cdc166a60088e5e99f5d0969dd2f06b80eecb9fb2be1f4e2d06b11de92ea51b47b3a7c24d621b5ae8e436f",
          "sha256": "3d334a852d36cdb8e812de7fd239148c0ea60447e909e8d40052491f47756ba9",
          "sha1": "a3b469076c07291596c5a010945fec90c698afc7",
          "md5": "0281d92fba5a11bafa97cdb59f77bc6e"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "controlify-forgified-2.1.2-mc1.20.1-forge.jar",
          "url": "controlify-forgified-2.1.2-mc1.20.1-forge.jar",
          "size": 6946940,
          "sha512": "dfff22afb23f70f51fb81391257c7cfe48f3031a37cdc166a60088e5e99f5d0969dd2f06b80eecb9fb2be1f4e2d06b11de92ea51b47b3a7c24d621b5ae8e436f",
          "sha256": "3d334a852d36cdb8e812de7fd239148c0ea60447e909e8d40052491f47756ba9",
          "sha1": "a3b469076c07291596c5a010945fec90c698afc7",
          "md5": "0281d92fba5a11bafa97cdb59f77bc6e"
        }
      ]
    }
  ]
}
