{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.echoellet",
    "module": "controlify-forgified",
    "version": "2.1.2-mc1.20.1-forge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "controlify-forgified-2.1.2-mc1.20.1-forge-sources.jar",
          "url": "controlify-forgified-2.1.2-mc1.20.1-forge-sources.jar",
          "size": 2012750,
          "sha512": "bc2f3551c8af29e85e0ec044de60957d17e6a205e700307b621b8613e83686395c341813bdf6eed6d00822b597a5f98f05d6f9d7eabae9c2549e0ad680dda33d",
          "sha256": "e48e10890a59ca79101026a393ccd561d283389f5f22ef504b8c3cfd09bb7743",
          "sha1": "4f002e929b9e8d1d9c1617d275db4c8984f39303",
          "md5": "c2b67bf7aa412898c504a08230979497"
        }
      ]
    },
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "controlify-forgified-2.1.2-mc1.20.1-forge.jar",
          "url": "controlify-forgified-2.1.2-mc1.20.1-forge.jar",
          "size": 6984505,
          "sha512": "51502cf409cc534fb161dedba95cb70da7a6af27d7c1138befc2032497a6915a2a0cd09c747d94b10ebbdd375a251d8da8fb73215fdb9d106eec9075893acc3b",
          "sha256": "96c8b985bad2dc3d488532d04908408286308cb546feaded42119896b962f3dc",
          "sha1": "1a5ef6331f937ee69d059ae1fd327bc8de08c466",
          "md5": "63210df41ab51fb7fe867f735baeb360"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "controlify-forgified-2.1.2-mc1.20.1-forge.jar",
          "url": "controlify-forgified-2.1.2-mc1.20.1-forge.jar",
          "size": 6984505,
          "sha512": "51502cf409cc534fb161dedba95cb70da7a6af27d7c1138befc2032497a6915a2a0cd09c747d94b10ebbdd375a251d8da8fb73215fdb9d106eec9075893acc3b",
          "sha256": "96c8b985bad2dc3d488532d04908408286308cb546feaded42119896b962f3dc",
          "sha1": "1a5ef6331f937ee69d059ae1fd327bc8de08c466",
          "md5": "63210df41ab51fb7fe867f735baeb360"
        }
      ]
    }
  ]
}
