plugins {
    id 'java-library'
    id 'maven-publish'
    // github.com/neoforged/ModDevGradle/blob/main/LEGACY.md
    id 'net.neoforged.moddev.legacyforge' version '2.0.116'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
}

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"


legacyForge {
    version = "${minecraft_version}-${forge_version}"
    validateAccessTransformers = true

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.minecraft_version
    }

    runs {
        client {
            client()

            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    mavenCentral()
    maven {
        name = "xanderRepoReleases"
        url = uri("https://maven.isxander.dev/releases")
    }

    maven {
        url("https://maven.quiltmc.org/repository/release")
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${project.property('deps.mixinExtras')}"))
    modImplementation(jarJar("io.github.llamalad7:mixinextras-forge:${project.property('deps.mixinExtras')}"))

    modCompileOnly("maven.modrinth:fancymenu:3.7.0-1.20.1-forge")
    modCompileOnly("maven.modrinth:simple-voice-chat:forge-1.20.1-2.6.6")
    modImplementation("dev.isxander:yet-another-config-lib:3.6.6+1.20.1-forge")

    // Bundles these dependencies in the JAR file (https://docs.minecraftforge.net/en/fg-5.x/dependencies/#non-minecraft-dependencies)
    implementation(jarJar("dev.isxander:libsdl4j:${project.property('deps.sdl3Target')}-${project.property('deps.sdl34jBuild')}"))
    additionalRuntimeClasspath("dev.isxander:libsdl4j:${project.property('deps.sdl3Target')}-${project.property('deps.sdl34jBuild')}")

    implementation(jarJar("dev.isxander:steamdeck4j:${project.property('deps.steamdeck4j')}"))
    additionalRuntimeClasspath("dev.isxander:steamdeck4j:${project.property('deps.steamdeck4j')}")

    implementation(jarJar(("org.hid4java:hid4java:${project.property('deps.hid4java')}")))
    additionalRuntimeClasspath("org.hid4java:hid4java:${project.property('deps.hid4java')}")
    implementation("net.java.dev.jna:jna:5.18.1") // Transitive dependency of hid4java

    implementation(jarJar("org.jetbrains:annotations:24.0.0"))

    implementation "org.quiltmc.parsers:json:${project.property('deps.quiltparsers')}"

    modImplementation("maven.modrinth:embeddium:0.3.31+mc1.20.1")
    modImplementation("maven.modrinth:oculus:1.20.1-1.8.0")
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_description        : mod_description,
            mod_author             : mod_authors,
            pack_format            : 15
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
legacyForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"

    config "${mod_id}.mixins.json"
    config "${mod_id}-platform.forge.mixins.json"
}

jar {
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}-platform.forge.mixins.json"
    ])
}

// Copy-paste from: https://github.com/isXander/Controlify/blob/multiversion/dev/build.gradle.kts#L130-L187
// but with quick migration to MinecraftForge & Gradle Groovy
/*
START
Include native libraries for SDL3 in the jar.
 */
def nativeTargets = [
        [classifier: "linux-aarch64", fileExt: "so", jnaPrefix: "linux-aarch64/", fileName: "libSDL3", configName: "offlineNativeLinuxAarch64"],
        [classifier: "linux-x86_64", fileExt: "so", jnaPrefix: "linux-x86-64/", fileName: "libSDL3", configName: "offlineNativeLinuxX86_64"],
        [classifier: "macos-aarch64", fileExt: "dylib", jnaPrefix: "darwin-aarch64/", fileName: "libSDL3", configName: "offlineNativeMacArm"],
        [classifier: "macos-x86_64", fileExt: "dylib", jnaPrefix: "darwin-x86-64/", fileName: "libSDL3", configName: "offlineNativeMacIntel"],
        [classifier: "windows-x86_64", fileExt: "dll", jnaPrefix: "win32-x86-64/", fileName: "SDL3", configName: "offlineNativeWinX86_64"]
]

nativeTargets.each { configurations.create(it.configName) }
configurations.create("nativeHashes")

dependencies {
    nativeTargets.each {
        def sdl3Target = project.property("deps.sdl3Target")
        "${it.configName}" "dev.isxander:libsdl4j-natives:${sdl3Target}:${it.classifier}@${it.fileExt}"
        nativeHashes "dev.isxander:libsdl4j-natives:${sdl3Target}:${it.classifier}@${it.fileExt}.md5"
    }
}

task prepareNativeResources(type: Sync) {
    group = "controlify/internal"
    into "$buildDir/generated-resources/sdl-natives"

    nativeTargets.each { t ->
        from(configurations[t.configName]) { into t.jnaPrefix; rename { "${t.fileName}.${t.fileExt}" } }
    }

    from(configurations.nativeHashes) { into "sdl3-hashes/" }
}

processResources.from(prepareNativeResources)
processResources.dependsOn prepareNativeResources
/*
END
Include native libraries for SDL3 in the jar.
 */

