org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
parchment_mappings_version=2023.09.03
mod_id=controlify
mod_name=Controlify Forgified (Unofficial)
mod_license=LGPL-3.0-or-later
mod_version=2.1.2
mod_group_id=dev.echoellet
mod_authors=isXander, EchoEllet (unofficial port)
mod_description=Unofficial Forge 1.20.1 port that adds the best controller support to Minecraft Java Edition!

deps.sdl3Target=3.2.18.release-3.2.18
deps.sdl34jBuild=79
deps.hid4java=0.8.0
deps.quiltparsers=0.3.0
deps.steamdeck4j=1.1.7
deps.mixinExtras=0.5.0-beta.4
