{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.echoellet",
    "module": "controlify-forgified",
    "version": "2.1.3-mc1.20.1-forge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "controlify-forgified-2.1.3-mc1.20.1-forge-sources.jar",
          "url": "controlify-forgified-2.1.3-mc1.20.1-forge-sources.jar",
          "size": 1978356,
          "sha512": "9f1f7da9dff9a6deba0908bb185758274c71867fbc72139650228736259679ae6f8d851455a2f0b013cc25043e46eac820e7362528c8c966cd61752a3132f61c",
          "sha256": "5a9c48e62b83777605a82aa1401ed21fbf75bce013d48ab0ac89a1f3b5378e41",
          "sha1": "b958d3328eac687c053f7dada78cadcce4acfd8b",
          "md5": "3150aa2753ecce2cbfa17922db4ed6b4"
        }
      ]
    },
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "controlify-forgified-2.1.3-mc1.20.1-forge.jar",
          "url": "controlify-forgified-2.1.3-mc1.20.1-forge.jar",
          "size": 6971246,
          "sha512": "79c6c9de4e398766a435c40b7bc80a8f99b58ca53c88a325a33db3e7561767e7012a10da207420b8a247bd621df8bf889f1a6b317e9e941c6567470d1c283eb6",
          "sha256": "76e3e233e1e93cc6aba3b5f12cb6eae038bbbdd14668bf3c4ed43407946d4a60",
          "sha1": "b1ff6699d535883425ce1918a9417c98ecc22a4c",
          "md5": "15782418fd6be0500c41fa30771b5b65"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "controlify-forgified-2.1.3-mc1.20.1-forge.jar",
          "url": "controlify-forgified-2.1.3-mc1.20.1-forge.jar",
          "size": 6971246,
          "sha512": "79c6c9de4e398766a435c40b7bc80a8f99b58ca53c88a325a33db3e7561767e7012a10da207420b8a247bd621df8bf889f1a6b317e9e941c6567470d1c283eb6",
          "sha256": "76e3e233e1e93cc6aba3b5f12cb6eae038bbbdd14668bf3c4ed43407946d4a60",
          "sha1": "b1ff6699d535883425ce1918a9417c98ecc22a4c",
          "md5": "15782418fd6be0500c41fa30771b5b65"
        }
      ]
    }
  ]
}
