{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.echoellet",
    "module": "controlify-forgified",
    "version": "2.1.4-mc1.20.1-forge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "controlify-forgified-2.1.4-mc1.20.1-forge-sources.jar",
          "url": "controlify-forgified-2.1.4-mc1.20.1-forge-sources.jar",
          "size": 1978356,
          "sha512": "e69b2d2fb70e015f8116e4552be3897bdabf6fade2a228bc5461cdde7196ae5bfe6e56d8037067ea353c548243fdcc20321d1a830568732f43d190f267ef9c97",
          "sha256": "a59b984902088fc19ca9a3ca61aea7bec3d082df3a72c6e4630335b8bdfe1d90",
          "sha1": "9896e8888ae8d01811f1d65bd1cbb80f4fa86ea2",
          "md5": "38ea8e5c3dc62a0159abab711e656e43"
        }
      ]
    },
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "controlify-forgified-2.1.4-mc1.20.1-forge.jar",
          "url": "controlify-forgified-2.1.4-mc1.20.1-forge.jar",
          "size": 6949878,
          "sha512": "a3074c549f044c72d4444d419b33b2f0295821a62e1ec000652875be1005ecbcee4ca2c1d1767c7e1fd264d2d80352b4292ca5423ab8d9d8a9f0b0923ed53f74",
          "sha256": "e2857879c0499917357f06de166f6e087addd89517cd64f0b33b3936136a3bf5",
          "sha1": "c424d0a44571e1ae126894f3784c533c83fd6c78",
          "md5": "91ad8fc42b22ef50d120646b8aa9b0f7"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "controlify-forgified-2.1.4-mc1.20.1-forge.jar",
          "url": "controlify-forgified-2.1.4-mc1.20.1-forge.jar",
          "size": 6949878,
          "sha512": "a3074c549f044c72d4444d419b33b2f0295821a62e1ec000652875be1005ecbcee4ca2c1d1767c7e1fd264d2d80352b4292ca5423ab8d9d8a9f0b0923ed53f74",
          "sha256": "e2857879c0499917357f06de166f6e087addd89517cd64f0b33b3936136a3bf5",
          "sha1": "c424d0a44571e1ae126894f3784c533c83fd6c78",
          "md5": "91ad8fc42b22ef50d120646b8aa9b0f7"
        }
      ]
    }
  ]
}
